
//BUZZ ACTION TYPE
export const POST_BUZZ_FEED = "POST_BUZZ_FEED";
export const GET_BUZZ_FEED = "GET_BUZZ_FEED";
export const GET_LIKE = "GET_LIKE";
export const GET_DISLIKE = "GET_DISLIKE";
export const DELETE_BUZZ = "DELETE_BUZZ";

//COMPLAINT ACTION TYPE
export const ADD_COMPLAINT = "ADD_COMPLAINT";
export const SHOW_COMPLAINT = "SHOW_COMPLAINT";

//RESOLVE ACTION TYPE
export const UPDATE_COMPLAINT_STATUS = "UPDATE_COMPLAINT_STATUS";

//USER ACTION TYPE
export const ShOW_USER_PROFILE = "ShOW_USER_PROFILE";